version: '3'

services:
  postgres:
    image: 'postgres:13.3-alpine'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresmaster
      POSTGRES_DB: postgres
#    volumes:
#      - ./db-data/postgres/:/var/lib/postgresql/data/